name: Build and Deploy bridge client to azure.

on:
  workflow_dispatch:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - feature/build-and-deploy-workflow
  

jobs:
  build-and-upload:
    runs-on: self-hosted
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Bun
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # Install dependencies and build
      - name: Install dependencies and build with Bun
        run: |
          bun install
          bun run build

      # Get version from package.json
      # Get full version and major.minor version
      - name: Extract version details
        id: get-version
        run: |
          FULL_VERSION=`bun -e "console.write(require('./packages/bridge-js/package.json').version)"`
          MAJOR_MINOR_VERSION=$(echo $FULL_VERSION | cut -d. -f1,2)
          echo "full_version=$FULL_VERSION" >> $GITHUB_ENV
          echo "major_minor_version=$MAJOR_MINOR_VERSION" >> $GITHUB_ENV

      - name: Login to Azure
        run: |
          az login --identity --allow-no-subscriptions          

      # Upload to Azure Blob Storage
      - name: Upload files to Azure Blob
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload \
              --account-name straddlewidgets \
              --container-name bridge \
              --name "bridge-js-umd.bundle.js" \
              --file "packages/bridge-js/dist/bridge-js-umd-${{ env.full_version }}.js"
            az storage blob upload \
              --account-name straddlewidgets \
              --container-name bridge \
              --name "bridge-js-umd.bundle.js" \
              --file "packages/bridge-js/dist/bridge-js-umd-${{ env.major_minor_version }}.js"              
            az storage blob upload \
              --account-name straddlewidgets \
              --container-name bridge \
              --name "bridge-js-esm-bundle.js" \
              --file "packages/bridge-js/dist/bridge-js-esm-${{ env.full_version }}.js"
            az storage blob upload \
              --account-name straddlewidgets \
              --container-name bridge \
              --name "bridge-js-esm-bundle.js" \
              --file "packages/bridge-js/dist/bridge-js-esm-${{ env.major_minor_version }}.js"              
            az storage blob upload \ }}.js"
              az storage blob upload \
              --account-name straddlewidgets \
              --container-name bridge \
              --name "bridge-js-cjs-bundle.js" \
              --file "packages/bridge-js/dist/bridge-js-cjs-${{ env.full_version }}.js"
            az storage blob upload \
              --account-name straddlewidgets \
              --container-name bridge \
              --name "bridge-js-cjs-bundle.js" \
              --file "packages/bridge-js/dist/bridge-js-cjs-${{ env.major_minor_version }}.js"
